Feature
maherramadan78/Myportfolio pull request #4
Opened 2022-09-27 17:59 UTC by maherramadan78

finish mobile  porfolio project

2022-09-27 19:55 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 
## Hi @jossi30, I'm @MaganaAsiati, your reviewer for this PR  :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close-gif-4](https://user-images.githubusercontent.com/95297251/191952218-b7185270-c02b-4e4d-89af-eae77fcd8bea.gif)

## Highlights

- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:

## Required Changes ♻️
https://github.com/maherramadan78/Myportfolio/blob/147dc28f5a340b6f2230de2aec530ebcf41538f0/index.html#L194-L196
- [ ] Kindly make sure the `see project `button looks like it shows in the Figma design  in the margins  (top, bottom, left, right) and follows the button styling: Active, Hover, and Pressed [see design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=23%3A10) as required in the project :grinning:  :grinning:  :grinning: 

## Your design
 
![image](https://user-images.githubusercontent.com/95297251/192617193-f37fef4b-cd96-4266-a562-d68acf59fcdf.png)

## Figma design

![image](https://user-images.githubusercontent.com/95297251/192617338-7506ed83-7963-48a8-b866-52b89fbe004c.png

- [x]  I am sure you spent a lot of time working on contact the part ( section ) but, smiling_face_with_tear: is not part of the requirements yet. Kindly remove it :grin: You will work on it later with better material. :+1: 
- [ ] Kindly reduce the font size of the cards text and  add some space between the container of your card so that it will make your design stick to the Figma design provided:grinning: :grinning: :grinning: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
- [ ] [OPTIONAL]  make sure all icons images are displayed properly and make the container of your home page correctly centered as I show in the picture below on Figma design  :grinning: :grinning: :grinning: 



 ## Your design 

![image](https://user-images.githubusercontent.com/95297251/192621259-973e5c97-5c1b-4731-89c1-ae7d5ecb6608.png)

## Figma design 

![image](https://user-images.githubusercontent.com/95297251/192620604-bf726357-f26c-49b9-a6f0-a81c22b406d2.png)
- [ ] [OPTIONAL] Please make sure that all your changes are visible in your current pull request so that your code reviewer could see the changes you have done.:grinning: :grinning: :grinning: 
 - [ ] [OPTIONAL]  Kindly give the meaning full name to your class so that it will make your code more readable  :grinning: :grinning: :grinning: 
- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future. :heavy_check_mark:👨🏻‍💻
- [ ] kindly  Add a meaningful description to your pull request in the future which gives more information about what you implement in this milestone :heavy_check_mark:👨🏻‍💻


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-09-27 19:55 UTC, MaganaAsiati commented on index.html
> +<body>
- [ ] Kindly make sure the body of your page takes the max screen so that it will remove the scrolling button from left to write and your mobile version design will match the Figma design  :grinning:  :grinning:  :grinning:  :grinning: 

 ## Your design 
![image](https://user-images.githubusercontent.com/95297251/192618634-6478a95f-58e5-4cb2-9b4d-e29c0aa1123d.png)

## Figma design

![image](https://user-images.githubusercontent.com/95297251/192619418-3d975227-1d59-43b1-a3b1-74fc4e05a8b5.png)

2022-10-25 17:48 UTC, maherramadan78 commented
Fix the conflict errors

2022-10-25 17:52 UTC, maherramadan78 commented
I ' m repeating my block , this project was already approved.
I fix some a few things in the css style and change a few code in html like the section.

2022-10-25 18:33 UTC, aimalamiri requested changes
Hi @maherramadan78, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![AlmostThereReachGIF](https://user-images.githubusercontent.com/34779928/191347504-9f70659c-a01f-48a1-ad46-b8722d46ffca.gif)

## Highlights

- The mobile version is designed very well and looks fantastic ✔️ ⭐
- Good job for using the right GitHub Flow 💯
- Awesome file organization 🗃️
- Commits are descriptive and meaningful 👍
- Linters are properly set up and passing 🟢 👍

## Required Changes ♻️

- [ ] Good job, but please make sure to add some space to your logo in the header.

![image](https://user-images.githubusercontent.com/34779928/197853421-1311daa7-6e86-456c-921e-0181ef3dc84c.png)

- [ ] It's almost done, but the last project has no `See Project` button. Kindly add that as well.
![image](https://user-images.githubusercontent.com/34779928/197853881-8fd9cb44-dba3-4275-80a7-139da4629944.png)



_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-26 00:14 UTC, Alfredbis29 approved these changes
Hi @maherramadan78 , 

### **STATUS: APPROVED** :clap: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

## Optional suggestions
- [ ]  Everything is now OK, however I believe it would be better if you removed the black border that surrounds all of your content so that your project matches the figma one.Kindly fix this :point_down: 
your design :point_down: 
![remove](https://user-images.githubusercontent.com/88894525/197904602-536d7156-1951-417f-b046-5f7c1585f4c8.png)

Figma Design:
![follow](https://user-images.githubusercontent.com/88894525/197904632-f4ccefa9-2093-45ca-bba2-3cefbd2a834b.png)


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-26 05:53 UTC, merged